import Head from 'next/head'
import AboutUs from '../components/AboutUs'
import Portfolios from '../components/Portfolios'
import Skills from '../components/Skills'
import SliderSection from '../components/SliderSection'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Developer Sairaj Aftab</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <SliderSection/>
        <AboutUs/>
        <Skills/>
        <Portfolios/>
      </main>

      <footer>

      </footer>
    </div>
  )
}
